# Generated by Django 3.0.7 on 2020-06-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firecommandcenter', '0002_auto_20200608_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='thrid_class',
            new_name='third_class',
        ),
    ]
