# Generated by Django 3.0.7 on 2020-06-15 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points_reward', models.IntegerField()),
                ('gems_reward', models.IntegerField()),
                ('requirements_needed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FireRankRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firerank.FireRank')),
                ('requirements_met', models.ManyToManyField(to='firerank.FireRankRequirement')),
            ],
        ),
    ]
