# Generated by Django 3.0.7 on 2020-06-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireshop', '0002_shopitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitemredeem',
            name='additional_notes',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
