# Generated by Django 3.0.7 on 2020-06-12 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firecore', '0002_populate_class_trees'),
        ('fireshop', '0003_shopitemredeem_additional_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_number', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fireshop.Event')),
                ('fifth_character', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firecore.Character')),
                ('first_character', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firecore.Character')),
                ('fourth_character', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firecore.Character')),
                ('second_character', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firecore.Character')),
                ('third_character', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firecore.Character')),
            ],
        ),
    ]
