# Generated by Django 3.0.7 on 2020-06-15 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fireshop', '0004_eventparty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventattendancecategory',
            old_name='points_ammount',
            new_name='points_amount',
        ),
        migrations.RenameField(
            model_name='playerpoints',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='shopitem',
            old_name='points_ammount',
            new_name='points_cost',
        ),
        migrations.RemoveField(
            model_name='playerpoints',
            name='id',
        ),
        migrations.RemoveField(
            model_name='playerpointshistory',
            name='event',
        ),
        migrations.RemoveField(
            model_name='playerpointshistory',
            name='event_attendance_category',
        ),
        migrations.AddField(
            model_name='playerpointshistory',
            name='amount_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerpointshistory',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerpoints',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shop_points', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
