# Generated by Django 3.0.7 on 2020-06-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireshop', '0006_auto_20200615_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendance',
            name='attendance_type',
            field=models.CharField(choices=[('going', 'Sim'), ('maybe', 'Talvez'), ('notgoing', 'Não')], max_length=100),
        ),
    ]
