# Generated by Django 3.0.7 on 2020-06-15 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fireshop', '0007_auto_20200615_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendance',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
