# Generated by Django 3.0.7 on 2020-06-15 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fireshop', '0008_eventattendance_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendance',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
