# Generated by Django 3.0.7 on 2020-06-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireshop', '0009_eventattendance_confirmation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendance',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
