# Generated by Django 3.0.7 on 2020-06-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireshop', '0011_auto_20200625_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendance',
            name='attendance_type',
            field=models.CharField(choices=[('going', 'Vou'), ('maybe', 'Talvez'), ('notgoing', 'Não Vou')], max_length=100),
        ),
        migrations.DeleteModel(
            name='EventAttendanceConfirmation',
        ),
    ]
