# Generated by Django 3.0.7 on 2020-06-26 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fireshop', '0012_auto_20200626_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendanceConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_date', models.DateTimeField(auto_now_add=True)),
                ('attendance_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fireshop.EventAttendanceCategory')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fireshop.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
