# Generated by Django 3.0.7 on 2020-06-11 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_type', models.CharField(choices=[('FOOD', 'Tenda de Comida'), ('BUFF', 'Buffs de Pardoner'), ('WEPBUFF', 'Buffs para Arma'), ('ENCHANT', 'Enchants Peito e Calça'), ('AWAK', 'Awakening'), ('ROAST', 'Limpa Gemas'), ('SEX', 'Troca de Sexo'), ('REPLEATHER', 'Repair de Leather'), ('REPCLOTH', 'Repair de Cloth'), ('REPPLATE', 'Repair de Plate'), ('REPAIR', 'Repair sem Arts')], max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firecore.ClassTree')),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_gtw_char', models.BooleanField(default=True)),
                ('is_boruta_char', models.BooleanField(default=True)),
                ('build_type', models.CharField(choices=[('CTR', 'Controle'), ('DPS', 'Dano'), ('SUP', 'Suporte'), ('TNK', 'Tanque')], max_length=100, null=True)),
                ('class_tree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='firecore.ClassTree')),
                ('first_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='firecore.Class')),
                ('second_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='firecore.Class')),
                ('third_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='firecore.Class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
