# Generated by Django 3.0.7 on 2020-06-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firecore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
    ]
