# Generated by Django 3.0.7 on 2020-06-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firecore', '0003_auto_20200608_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='build_type',
            field=models.CharField(choices=[('CTR', 'Controle'), ('DPS', 'Dano'), ('SUP', 'Suporte'), ('TNK', 'Tanque')], max_length=100, null=True),
        ),
    ]
