# Generated by Django 3.0.7 on 2020-06-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firecore', '0005_character_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_boruta_char',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='character',
            name='is_gtw_char',
            field=models.BooleanField(default=True),
        ),
    ]
