# Generated by Django 3.0.7 on 2020-06-09 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firecore', '0006_auto_20200609_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_type', models.CharField(choices=[('FOOD', 'Tenda de Comida'), ('BUFF', 'Buffs de Pardoner'), ('WEPBUFF', 'Buffs para Arma'), ('ENCHANT', 'Enchants Peito e Calça'), ('AWAK', 'Awakening'), ('ROAST', 'Limpa Gemas'), ('SEX', 'Troca de Sexo'), ('REPLEATHER', 'Repair de Leather'), ('REPCLOTH', 'Repair de Cloth'), ('REPPLATE', 'Repair de Plate'), ('REPAIR', 'Repair sem Arts')], max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
