# Generated by Django 3.0.7 on 2020-06-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firecore', '0007_playershop'),
        ('firecore', '0008_auto_20200609_1559'),
    ]

    operations = [
    ]
